### PR TITLE
Compatibility patch for newer versions of used libraries

### PR DESCRIPTION
**Pull request by SirBoonami**
See SirBoonami/hbro@af09388376f355ce224e47fd99c62c2d1e59d15c . Similar, but slightly different issue. New versions of some libs made hbro unable to compile.

### CODE REVIEW

**Comment by k0ral** [comment]
Fixed in bb61b830c4dbff8124b443bd0026faa9d889d886, new release pushed on hackage.
Thank you !

**Comment by SirBoonami** [comment]
Just installed it. The new release itself works like a charm, but the supplied default config doesn't compile anymore.

    Configuration '/home/boonami/.hbro/hbro.hs' changed. Recompiling.
    Error occurred while loading configuration file.
    Launching custom binary /home/boonami/.cache/hbro/hbro-linux-x86_64
    
    ERROR 
    /home/boonami/.hbro/hbro.hs:12:54: error:
        Module ‘Hbro.Config’ does not export ‘homePageL’

**Comment by k0ral** [comment]
Fixed in last release (1.7.0.0). Hopefully everything is alright now :) .

**Comment by SirBoonami** [comment]
Thank you very much =)

**Pull request closed without merging**
